apiVersion: v1
kind: Pod
metadata:
  name: grid
  labels:
    app: grid
spec:
  containers:
    - image: selenium/hub:3.141.59
      name: grid
  ports:
    - containerPort: 8080
      protocol: TCP
  selector:
    app: grid
