apiVersion: v1
kind: Service
metadata:
  name: chrome-service
spec:
  ports:
    - name: node-port
      port: 5555
      targetPort: 5555
      protocol: TCP
    - name: node-port-grid
      port: 4444
      targetPort: 4444
      protocol: TCP
  selector:
    app: node
